accounts/urls.py
from django.urls import path
from .views import (
     HomeView, LoginUserView, RegistUserView, LogoutUserView,StaffUserView,
     ProfileView, ProfileEditView,PasswordChangeView,
     PasswordResetView,PasswordResetConfirmView
)

app_name = 'accounts'

urlpatterns = [
    path('home/', HomeView.as_view(), name='home'),
    path('login_user/', LoginUserView.as_view(), name='login_user'),
    path('regist_user/', RegistUserView.as_view(), name='regist_user'),
    path('staff_user/', StaffUserView.as_view(), name='staff_user'),
    path('profile/', ProfileView.as_view(), name='profile'),
    path('profile/<int:pk>/edit/', ProfileEditView.as_view(),name='profile_edit'),
    path('password_change/',PasswordChangeView.as_view(),name = 'password_change'),
    path('password_reset/', PasswordResetView.as_view(), name='password_reset'),
    path('password_reset/confirm/<uidb64>/<token>/', PasswordResetConfirmView.as_view(), name='password_reset_confirm'),
    path('logout_user/', LogoutUserView.as_view(), name='logout_user'),

]

daily_report/urls.py
from django.urls import path
from .views import (
    ReportListView ,ReportStartView ,ReportEndView,ReportDetailView,ReportDeleteView,
    RepoetStartInspectionView,ReportEndEditView,ReportLogoutConfirm,
    StockEditView,StockListView,StockDeleteView,
    ShippingStartView,ShippingDetailView,ShippingListView,ShippingDeleteView
)
app_name =  'daily_report'

urlpatterns = [
    path('report_list/', ReportListView.as_view(), name='report_list'),
    path('report_start/',ReportStartView.as_view(), name='report_start'),
    path('report_detail/<int:pk>/',ReportDetailView.as_view(),name='report_detail'),
    path('report_detail/<int:pk>/end/', ReportEndView.as_view(), name='report_end'),
    path('report_detail/<int:pk>/endedit/', ReportEndEditView.as_view(), name='report_endedit'),
    path('report_delete/<int:pk>/',ReportDeleteView.as_view(), name='report_delete'),
    path('report_start_inspection/',RepoetStartInspectionView.as_view(),name='report_start_inspection'),

    path('shipping_list/', ShippingListView.as_view(), name='shipping_list'),
    path('shipping_start/', ShippingStartView.as_view(), name='shipping_start'),
    path('shipping_detail/<int:pk>/',ShippingDetailView.as_view(),name='shipping_detail'),
    path('shipping_delete/<int:pk>/',ShippingDeleteView.as_view(),name='shipping_delate'),

    path('stocks_list/', StockListView.as_view(), name='stock_list'),
    path('stocks/<int:pk>/edit/', StockEditView.as_view(), name='stock_edit'),
    path('stocks_delete/<int:pk>/', StockDeleteView.as_view(), name='stock_delete'),

    path('logout/',ReportLogoutConfirm.as_view(),name='logout'),
]

production_control_project/urls.py
from django.contrib import admin
from django.urls import path, include
from django.views.generic import RedirectView

from django.conf import settings
from django.conf.urls.static import static


urlpatterns = [
    path('', RedirectView.as_view(url='/accounts/home/', permanent=True)),
    path('admin/', admin.site.urls),
    path('accounts/', include('accounts.urls')),
    path('daily_report/', include('daily_report.urls')),
    path('product_management/',include('product_management.urls'))
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

product_management/models.py
from django.db import models
from accounts.models import Users
from daily_report.models import Products
from datetime import datetime
# Create your models here.

#成形品---------------------------------------------------------------
class Molding(models.Model):
    product = models.ForeignKey(
        Products, on_delete=models.CASCADE, verbose_name='製品名'
    )
    lot_number = models.CharField(max_length=10, verbose_name='ロッド番号',default='')
    good_molding = models.IntegerField(verbose_name="優良成形数")
    bad_molding = models.IntegerField(verbose_name="不良成形数")
    user = models.ForeignKey(
        Users, on_delete=models.CASCADE, verbose_name='成形担当ユーザー名',null=True
    )
    memo = models.CharField(max_length=255,verbose_name="引き継ぎメモ",null=True,blank=True)
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)

    class Meta:
        verbose_name = '成形品'
        db_table = 'molding'

    def __str__(self):
        if self.user:
          return self.product.name + ':' + self.lot_number + ':' + self.user.username
        else:
          return self.product.name + ':' + self.lot_number + ':No User'
#納品先---------------------------------------------------------------
class Delivery(models.Model):
    delivery_name = models.CharField(max_length=50,verbose_name='納品先会社名')
    delivery_code = models.CharField(max_length=10,verbose_name='納品先コード')

    class Meta:
        verbose_name = '納品先'
        db_table = 'delivery'

    def __str__(self):
        return self.delivery_name


#在庫---------------------------------------------------------------
class Stock(models.Model):
    product = models.ForeignKey(
        Products, on_delete=models.CASCADE, verbose_name='製品名'
    )
    lot_number = models.CharField(max_length=10, verbose_name='ロッド番号',default='')
    stocks = models.IntegerField(verbose_name="在庫数")
    molding_user = models.ForeignKey(
        Users, on_delete=models.CASCADE, verbose_name='成形担当ユーザー名',null=True,related_name='molding_stock_set',
    )
    molding_time = models.DateTimeField(verbose_name='成形日時', default=datetime(2001, 1, 1, 0, 0, 0))
    inspection_user = models.ForeignKey(
        Users, on_delete=models.CASCADE, verbose_name='検査担当ユーザー名',null=True,related_name='inspection_stock_set',
    )
    memo = models.CharField(max_length=255,verbose_name="引き継ぎメモ",null=True,blank=True)
    created_at = models.DateTimeField(verbose_name='検査日時',auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)

    class Meta:
        verbose_name = '在庫'
        db_table = 'stock'

    def __str__(self):
        return '[' + self.created_at.strftime('%Y-%m-%d') + ']' + ':' + self.product.name + ':' + self.lot_number + ':' +'「' + '在庫数'+ '=' + '残り' + str(self.stocks) + '」'
#出荷---------------------------------------------------------------
class Shipping(models.Model):
    product = models.ForeignKey(
        Products, on_delete=models.CASCADE,verbose_name='製品名',default=''
    )
    delivery = models.ForeignKey(
        Delivery, on_delete=models.CASCADE, verbose_name='納品先'
    )
    user = models.ForeignKey(
        Users, on_delete=models.CASCADE, verbose_name='作業者名',null=True
    )
    shipping_day = models.DateField(verbose_name='出荷日')
    shipments_required = models.IntegerField(verbose_name='出荷必要数')
    memo = models.CharField(max_length=255,verbose_name="引き継ぎメモ",null=True,blank=True)
    stock1 = models.ForeignKey(
        Stock, on_delete=models.CASCADE, verbose_name='使用在庫1',related_name='stock1_set',null=True
    )
    stock2 = models.ForeignKey(
        Stock, on_delete=models.CASCADE, verbose_name='使用在庫2',related_name='stock2_set',null=True
    )
    stock3 = models.ForeignKey(
        Stock, on_delete=models.CASCADE, verbose_name='使用在庫3',related_name='stock3_set',null=True
    )
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)

    class Meta:
        verbose_name = '出荷'
        db_table = 'shipping'

    def __str__(self):
        return str(self.delivery) + ':' + self.product.name + ':' + str(self.stock1) + ':' + str(self.stock2) + ':' + str(self.stock3) 


    

daily_report/forms.py
from django import forms

from .models import Report
from .models import Business,Products
from product_management.models import Molding, Shipping, Stock
from accounts.models import Users

from datetime import date
today = date.today()

from django.http import JsonResponse

#ランダム数値
import random 
import string

#--------------------------------------------------------------------------------------------------
class ReportStartForm(forms.ModelForm):

    class Meta:
        model = Report
        fields = ['product', 'business','good_product']

    def __init__(self, *args, **kwargs):
        self.user = kwargs.pop('user', None)
        super(ReportStartForm, self).__init__(*args, **kwargs)
        
        if self.user and self.user.department:
            # ユーザーの部署と紐づく業務内容のみを選択肢として表示
            self.fields['business'].queryset = Business.objects.filter(department=self.user.department)


    #userフィールドに自動でリクエストユーザーをする。
    def save(self, commit=True):
        report = super(ReportStartForm, self).save(commit=False)
        if self.user:
            report.user = self.user

        #lot_numberにランダムの整数値を生成する.その時にreportモデルにあるlot_numberと被らないようにする。ユーザー部署が製造部の時だけ
        if self.user and self.user.department.name == '製造部':
            while True:
                random_value = ''.join(random.choices(string.ascii_letters + string.digits, k=10))
                if not Report.objects.filter(lot_number=random_value).exists():
                    report.lot_number = random_value
                    break

        if commit:
            report.save()
        return report

#--------------------------------------------------------------------------------------------------
class ReportEndForm(forms.ModelForm):
    product = forms.CharField(label='製品名')
    business = forms.CharField(label='業務内容')
    
    memo = forms.CharField(label='引き継ぎ',initial='なし',widget=forms.TextInput(attrs={'style': 'width: 200px; height: 100px;'}))
    sets = forms.IntegerField(label='セット数')
    bad_product = forms.IntegerField(label='不良数')
    quantity = forms.IntegerField(label='取り数', disabled=True)
    
    class Meta:
        model = Report
        fields = ['user','lot_number','quantity',
                  'sets','bad_product','memo']

    #初期値設定
    def __init__(self, *args, **kwargs):
        self.user = kwargs.pop('user', None)
        super(ReportEndForm, self).__init__(*args, **kwargs)


        # ユーザーの部署と紐づく業務内容のみを選択肢として表示
        if self.user and self.user.department:
            self.fields['business'].queryset = Business.objects.filter(department=self.user.department)
            self.fields['user'].queryset = Users.objects.filter(department=self.user.department)

        
        #下のread_onlyだけでは、forinkeyで紐付けされているフィールドは編集できてしまうので、
        #詳細データからデータを引き出し初期値に登録し、上でフィールドをcharfieldsにすることで
        #編集できなくし、データにも保存できる。
        if 'instance' in kwargs and kwargs['instance']:
            
            initial_data ={
                'product': kwargs['instance'].product,
                'business': kwargs['instance'].business,
                'user': kwargs['instance'].user,
                'lot_number': kwargs['instance'].lot_number,
                'quantity': kwargs['instance'].product.quantity
            }
            self.initial.update(initial_data)
        


        #初期値に設定したデータを編集できないようにする
        for field_name in [ 'product', 'business', 'user','lot_number']:
            self.fields[field_name].widget.attrs['readonly'] = 'readonly'

        #業務内容が成形以外なら成形数は入力しない
        if  self.instance and self.instance.business.name not in ('成形','検査'):
            self.fields['sets'].required = False
            self.fields['bad_product'].required = False
            self.fields['quantity'].required = False
            self.fields['sets'].widget = forms.HiddenInput()
            self.fields['bad_product'].widget = forms.HiddenInput()
            self.fields['quantity'].widget = forms.HiddenInput()

        #業務内容が検査の場合、good_productの初期値をgood_moldingから持ってくる。formの見た目を変えている。
        if self.instance and self.instance .business.name == '検査':
            lot_number = self.instance.lot_number
            try:
                molding = Molding.objects.get(lot_number = lot_number)
                good_molding = molding.good_molding
                self.initial['quantity'] = good_molding

                self.fields['quantity'].label = '成形優良数'
                del self.fields['sets']
            except Molding.DoesNotExist:
                self.add_error('good_product', '該当するデータが見つかりませんでした。')

    def clean_sets(self):
        sets = self.cleaned_data.get('sets')
        if sets is not None:
            if sets < 0:
                raise forms.ValidationError('負の値を入力できません')
            elif sets == 0:
                raise forms.ValidationError('0は入力できません.0を入力する場合は、日報ごと削除してください')
        return sets

    def clean_bad_product(self):
        bad_product = self.cleaned_data.get('bad_product')
        if bad_product is not None:
            if bad_product < 0:
                raise forms.ValidationError('負の値を入力できません')
        return bad_product
    

#--------------------------------------------------------------------------------------------------
class ReportStartInspectionForm(forms.ModelForm):
    lot_number = forms.ChoiceField(label='成形品ロッドナンバー', choices=[])

    class Meta:
        model = Report
        fields = ['lot_number','business']

    def __init__(self, *args, **kwargs):
        self.user = kwargs.pop('user', None)
        super(ReportStartInspectionForm, self).__init__(*args, **kwargs)
        
        # Molding モデルから lot_number の値を取得して選択肢としてセットします

            # '検査部' の場合の条件を設定
        excluded_lot_numbers = Report.objects.filter(
            created_at__date=today,
            business__name='検査',  # '検査' という業務名に応じて調整
        ).values_list('lot_number', flat=True)
        
        all_molding_lot_numbers = Molding.objects.values_list('lot_number', flat=True).distinct()
        molding_lot_numbers = [lot_number for lot_number in all_molding_lot_numbers if lot_number not in excluded_lot_numbers]
        molding_choices = [(lot_number, lot_number) for lot_number in molding_lot_numbers]
        self.fields['lot_number'].choices = molding_choices

        #ユーザーの部署に合わせて業務内容を表示
        if self.user and self.user.department:
            self.fields['business'].queryset = Business.objects.filter(department=self.user.department)


    #userフィールドに自動でリクエストユーザーをする。
    def save(self, commit=True):
        report = super(ReportStartInspectionForm, self).save(commit=False)
        if self.user:
            report.user = self.user
        if commit:
            report.save()
        return report
    

    
#--------------------------------------------------------------------------------------------------
class ReportEndEditForm(forms.ModelForm):
    product = forms.CharField(label='製品名')
    business = forms.CharField(label='業務内容')
    bad_product = forms.IntegerField(label='不良数')
    good_product = forms.IntegerField(label='優良数')
    memo = forms.CharField(label='引き継ぎ',initial='なし',widget=forms.TextInput(attrs={'style': 'width: 200px; height: 100px;'}))
    
    class Meta:
        model = Report
        fields = ['user','lot_number','good_product',
                  'bad_product','memo']

    #初期値設定
    def __init__(self, *args, **kwargs):
        self.user = kwargs.pop('user', None)
        super(ReportEndEditForm, self).__init__(*args, **kwargs)


        # ユーザーの部署と紐づく業務内容のみを選択肢として表示
        if self.user and self.user.department:
            self.fields['business'].queryset = Business.objects.filter(department=self.user.department)
            self.fields['user'].queryset = Users.objects.filter(department=self.user.department)

        
        #詳細データからデータを引き出し初期値に登録
        if 'instance' in kwargs and kwargs['instance']:
            
            initial_data ={
                'product': kwargs['instance'].product,
                'business': kwargs['instance'].business,
                'user': kwargs['instance'].user,
                'lot_number': kwargs['instance'].lot_number,
                'good_product':kwargs['instance'].good_product,
                'bad_product':kwargs['instance'].bad_product,
                'memo': kwargs['instance'].memo
            }
            self.initial.update(initial_data)


        #初期値に設定したデータを編集できないようにする
        for field_name in [ 'product', 'business', 'user','lot_number']:
            self.fields[field_name].widget.attrs['readonly'] = 'readonly'

    def clean_good_product(self):
        good_product = self.cleaned_data.get('good_product')
        if good_product is not None:
            if good_product < 0:
                raise forms.ValidationError('負の値を入力できません')
            elif good_product == 0:
                raise forms.ValidationError('0は入力できません.0を入力する場合は、日報ごと削除してください')
        return good_product

    def clean_bad_product(self):
        bad_product = self.cleaned_data.get('bad_product')
        if bad_product is not None:
            if bad_product < 0:
                raise forms.ValidationError('負の値を入力できません')
        return bad_product
    


#-------------------------------------------------------------------------------------------------

class StockEditForm(forms.ModelForm):
    memo = forms.CharField(label='引き継ぎ',initial='なし',widget=forms.Textarea(attrs={'style': 'width: 200px; height: 100px; white-space:nomal;'}))
    stocks = forms.IntegerField(label='在庫数',required = False)
    class Meta:
        model = Stock
        fields = [ 'product','lot_number',
                  'molding_user','inspection_user',
                  'stocks','memo']
        
    def __init__(self, *args, **kwargs):
        super(StockEditForm, self).__init__(*args, **kwargs)


        for field_name in [ 'product','lot_number']:
            self.fields[field_name].widget.attrs['readonly'] = 'readonly'

        self.fields['molding_user'].queryset = Users.objects.filter(department__name='製造部')

templates/shipping/shipping_delete.html
{% extends "base.html" %}

{% block content %}
<h2>- 作業削除 -</h2>
<p><strong>作業を削除してもよろしいですか？</strong></p>
<form method="POST" id="delete-form">
    {% csrf_token %}
    <p>製品名:{{ shipping.product.name }}</p>
    <p>製品コード: {{ shipping.product.code }}</p>
    <p>納品先: {{ shipping.delivery }}</p>
    <p>担当ユーザー: {{ shipping.user.username }}</p>
    <p>出荷日時: {{ shipping.shipping_day }}</p>
    <p>出荷量: {{ shipping.shipments_required }}</p>
    <p>使用在庫１: {{ shipping.stock1}}</p>
    <p>使用在庫２: {{ shipping.stock2 }}</p>
    <p>使用在庫３: {{ shipping.stock3 }}</p>
    <p>引き継ぎ: {{ shipping.memo }}</p>
    
    <input type="submit" value="削除" onclick="confirmDelete()">
</form>


<p><a href="{% url 'daily_report:report_list' %}">ホーム画面に戻る</a></p>

<script>
    function confirmDelete() {
        if (confirm("作業を削除してもよろしいですか?\n***削除した場合、必ず在庫を調節してください。***")) {
            // OKをクリックしたときに削除を実行
            document.getElementById("delete-form").submit();
        }
    }
</script>

{% endblock %}

templates/shipping/shipping_detail.html
{% extends 'base.html' %}

{% block content %}
<h2>- 作業詳細 -</h2>
    <p>製品名: {{ shippingdetail.product.name }}</p>
    <p>製品コード: {{ shippingdetail.product.code }}</p>
    <p>納品先: {{ shippingdetail.delivery }}</p>
    <p>出荷担当者 {{ shippingdetail.user.username }}</p>
    <p>出荷日時: {{ shippingdetail.shipping_day }}</p>
    <p>出荷数: {{ shippingdetail.shipments_required }}</p>
    <p>引き継ぎ: {{ shippingdetail.memo }}</p>
    {% if shippingdetail.stock1 %}
    <p>使用在庫: {{ shippingdetail.stock1 }}</p>
    <p>使用在庫: {{ shippingdetail.stock2 }}</p>
    <p>使用在庫: {{ shippingdetail.stock3 }}</p>
    {% endif %}


    <p><button><a href="{% url 'daily_report:shipping_delate' shippingdetail.id %}">作業を削除する</a></button></p>

    <p><a href="{% url 'daily_report:report_list' %}">ホーム画面に戻る</a></p>

{% endblock %}

templates/shipping/shipping_start.html
{% extends "base.html" %}

{% block content %}
<h2>- 出荷詳細入力 -</h2>
<h3>出荷作業終了時の詳細を入力してください。</h3>
<form method="POST">
    {% csrf_token %}
    <div>
        {{ form.product.label_tag }}
        <select id="id_product" name="product">
            <option value="">選択してください</option>
            {% for product in product_choices %} 
                <option value="{{ product.id }}">{{ product.name }}</option>
            {% endfor %}
        </select>
    </div>
    <div>
        {{ form.delivery.label_tag }} 
        {{ form.delivery }}
    </div>
    <div>
        {{ form.shipments_required.label_tag }} 
        {{ form.shipments_required }}
    </div>
    <div>
        {{ form.shipping_day.label_tag }}
        {{ form.shipping_day }}
    </div>

    <div>
        {{ form.stock1.label_tag }}
        <select id="id_stock1" name="stock1" >
            <option value="">選択してください</option>
            {% for stock in stock1 %} 
                <option value="{{ stock.id }}">{{ stock.name }}</option>
            {% endfor %}
        </select>
        <div style="display: flex; align-items: center;">
            {{ form.sets1.label_tag }} 
            <input type="number" id="id_sets1" name="sets1" style="display:none; margin-left: 10px;">
        </div>
    </div>

    <div>
        {{ form.stock2.label_tag }}
        <select id="id_stock2" name="stock2">
            <option value="">選択してください</option>
            {% for stock in stock2 %} 
                <option value="{{ stock.id }}">{{ stock.name }}</option>
            {% endfor %}
        </select>
        <div style="display: flex; align-items: center;">
            {{ form.sets2.label_tag }} 
            <input type="number" id="id_sets2" name="sets2" style="display:none; margin-left: 10px;">
        </div>
    </div>
    
    <div>
        {{ form.stock3.label_tag }}
        <select id="id_stock3" name="stock3">
            <option value="">選択してください</option>
            {% for stock in stock3 %} 
                <option value="{{ stock.id }}">{{ stock.name }}</option>
            {% endfor %}
        </select>
        <div style="display: flex; align-items: center;">
            {{ form.sets3.label_tag }} 
            <input type="number" id="id_sets3" name="sets3" style="display:none;margin-left: 10px;">
        </div>
    </div>
       
    <div>
        {{ form.memo.label_tag }}
        {{ form.memo }}
    </div>

    {% if form.errors %}
    <div class="custom-error-message">
        <p><strong>-------- エラーメッセージ ----------</strong></p>
        <ul style="list-style: none;">
            {% for field, error in form.errors.items %}
                <li>{{ field }}: {{ error }}</li>
            {% endfor %}
        </ul>
        <p><strong>---------------------------------------</strong></p>
    </div>
    {% endif %}
    <input type="submit" value="出荷記録を入力する">

</form>
<p><a href="{% url 'daily_report:report_list' %}">ホーム画面に戻る</a></p>

<script>

    document.addEventListener("DOMContentLoaded", function () {
    var productSelect = document.querySelector("#id_product");
    var stock1Select = document.querySelector("#id_stock1");
    var stock2Select = document.querySelector("#id_stock2");
    var stock3Select = document.querySelector("#id_stock3");
    var sets1Input = document.querySelector("#id_sets1");
    var sets2Input = document.querySelector("#id_sets2");
    var sets3Input = document.querySelector("#id_sets3");

    productSelect.value = localStorage.getItem('productValue') || '';
    stock1Select.value = localStorage.getItem('stock1Value') || '';
    stock2Select.value = localStorage.getItem('stock2Value') || '';
    stock3Select.value = localStorage.getItem('stock3Value') || '';

   
    var stockSelects = [stock1Select, stock2Select, stock3Select];

    stockSelects.forEach(function (selectElement) {
        selectElement.innerHTML = ''; // セレクトボックスをクリア

        addOption(selectElement, "選択してください", ""); // "選択してください" オプションを追加
    });


    function addOption(selectElement, text, value) {
        var option = document.createElement('option');
        option.text = text;
        option.value = value;
        selectElement.appendChild(option);
    }

    productSelect.addEventListener("change", function () {
        var selectedProduct = productSelect.value;

        stock1Select.innerHTML = '<option value="">在庫を選択してください</option>';
        stock2Select.innerHTML = '<option value="">在庫を選択してください</option>';
        stock3Select.innerHTML = '<option value="">在庫を選択してください</option>';

        if (selectedProduct) {
            // 選択した product に基づいて stock オプションを読み込む
            $.ajax({
                url: `{% url 'daily_report:shipping_start' %}`,
                type: "GET",
                data: { product_id: selectedProduct },
                success: function (data) {
                    // サーバーからのデータをもとに選択肢を動的に生成

                    updateSelectOptions(stock1Select, data);
                    updateSelectOptions(stock2Select, data);
                    updateSelectOptions(stock3Select, data);
                },
                error: function () {
                    // エラーハンドリング
                }
            });
        } else {
            
        }
        //setsの初期値をnoneにする
        sets1Input.style.display = "none";
        sets2Input.style.display = "none";
        sets3Input.style.display = "none";
        
    });

    // イベントリスナーを設定して、フォームの値が変更された際にローカルストレージに保存
    productSelect.addEventListener("change", function () {
        localStorage.setItem('productValue', productSelect.value);
        generateStockOptions(productSelect.value); // 選択した商品に基づいて選択肢を生成
    });

    // 初回ロード時に選択肢を生成
    if (productSelect.value) {
        generateStockOptions(productSelect.value);
    }


  
    stockSelects.forEach(function (selectElement) {
        selectElement.addEventListener("change", function () {
            var setsInput = sets1Input; // ここで適切な setsInput を選択

            if (selectElement === stock1Select) {
                setsInput = sets1Input;
            } else if (selectElement === stock2Select) {
                setsInput = sets2Input;
            } else if (selectElement === stock3Select) {
                setsInput = sets3Input;
            }

            if (selectElement.value === "") {
                setsInput.value = "";
                setsInput.disabled = true;
                setsInput.style.display = "none";
            } else {
                setsInput.value = "";
                setsInput.disabled = false;
                setsInput.style.display = "block";
            }
        });
    });

    function generateStockOptions(selectedProduct) {
        if (selectedProduct) {
            $.ajax({
                url: `{% url 'daily_report:shipping_start' %}`,
                type: "GET",
                data: { product_id: selectedProduct },
                success: function (data) {

                    stock1Select.innerHTML = '<option value="">在庫を選択してください</option>';
                    stock2Select.innerHTML = '<option value="">在庫を選択してください</option>';
                    stock3Select.innerHTML = '<option value="">在庫を選択してください</option>';
                    // サーバーからのデータをもとに選択肢を動的に生成
                    updateSelectOptions(stock1Select, data);
                    updateSelectOptions(stock2Select, data);
                    updateSelectOptions(stock3Select, data);
                },
                error: function () {
                    // エラーハンドリング
                }
            });
        }
    }


    function updateSelectOptions(selectElement, data, selectedProduct) {

        data.forEach(function (item) {
            if (item.product_id == selectedProduct) {
                var createdDate = new Date(item.created_at);
                var year = createdDate.getFullYear().toString().slice(-2);
                var month = ('0' + (createdDate.getMonth() + 1)).slice(-2);
                var day = ('0' + createdDate.getDate()).slice(-2);
                var formattedDate = year + '/' + month + '/' + day;
                var stockInfo = `[${formattedDate}] : ${item.product__name} : ${item.lot_number} : 在庫数 = 残り ${item.stocks}`;
                var option = document.createElement('option');
                option.value = item.id;
                option.textContent = stockInfo;
                selectElement.appendChild(option);
            }
        });
    }
    
});
    
</script>

{% endblock %}