accounts/urls.py
from django.urls import path
from .views import (
     HomeView, LoginUserView, RegistUserView, LogoutUserView,StaffUserView,
     ProfileView, ProfileEditView,PasswordChangeView,
     PasswordResetView,PasswordResetConfirmView
)

app_name = 'accounts'

urlpatterns = [
    path('home/', HomeView.as_view(), name='home'),
    path('login_user/', LoginUserView.as_view(), name='login_user'),
    path('regist_user/', RegistUserView.as_view(), name='regist_user'),
    path('staff_user/', StaffUserView.as_view(), name='staff_user'),
    path('profile/', ProfileView.as_view(), name='profile'),
    path('profile/<int:pk>/edit/', ProfileEditView.as_view(),name='profile_edit'),
    path('password_change/',PasswordChangeView.as_view(),name = 'password_change'),
    path('password_reset/', PasswordResetView.as_view(), name='password_reset'),
    path('password_reset/confirm/<uidb64>/<token>/', PasswordResetConfirmView.as_view(), name='password_reset_confirm'),
    path('logout_user/', LogoutUserView.as_view(), name='logout_user'),

]

product_management/urls.py
from django.urls import path
from .views import (
    StaffHomeView,StaffReportUserGraphView,StaffReportProductGraphView,
    StaffBusinessListView,StaffBusinessCreateView,StaffBusinessDeleteView,
    StaffProductCreateView,StaffProductListView,StaffProductEditView,StaffProductDeleteView,
    StaffStockListView,StaffStockEditView,StaffStockDeleteView,
    StaffReportListView, StaffReportEditView, StaffReportDeleteView,
    StaffMoldingListView, StaffMoldingEditView, StaffMoldingDeleteView,
    StaffUserListView,StaffUserDetailView,StaffUserDeleteView,
    StaffShippingListView,StaffShippingDetailView,StaffShippingDeleteView
)
app_name =  'product_management'

urlpatterns = [
  path('staff_home/',StaffHomeView.as_view(), name='staff_home'),
  path('staff_reportusergraph/',StaffReportUserGraphView.as_view(), name='staff_reportusergraph'),
  path('staff_reportproductgraph/',StaffReportProductGraphView.as_view(), name='staff_reportproductgraph'),

  path('staff_business_list/',StaffBusinessListView.as_view(), name='staff_business_list'),
  path('staff_business_create/',StaffBusinessCreateView.as_view(), name='staff_business_create'),
  path('staff_business_delete/<int:pk>/',StaffBusinessDeleteView.as_view(), name='staff_business_delete'),

  path('staff_stock_list/', StaffStockListView.as_view(), name='staff_stock_list'),
  path('staff_stock/<int:pk>/edit/', StaffStockEditView.as_view(), name='staff_stock_edit'),
  path('staff_stock_delete/<int:pk>/', StaffStockDeleteView.as_view(), name='staff_stock_delete'),

  path('staff_product_list/',StaffProductListView.as_view(), name='staff_product_list'),
  path('staff_product_create/', StaffProductCreateView.as_view(), name='staff_product_create'),
  path('staff_product/<int:pk>/edit/', StaffProductEditView.as_view(), name='staff_product_edit'),
  path('staff_product_delete/<int:pk>/', StaffProductDeleteView.as_view(), name='staff_product_delete'),

  path('staff_report_list/', StaffReportListView.as_view(), name='staff_report_list'),
  path('staff_report/<int:pk>/edit/', StaffReportEditView.as_view(), name='staff_report_edit'),
  path('staff_report_delete/<int:pk>/', StaffReportDeleteView.as_view(), name='staff_report_delete'),

  path('staff_molding_list/', StaffMoldingListView.as_view(), name='staff_molding_list'),
  path('staff_molding/<int:pk>/edit/', StaffMoldingEditView.as_view(), name='staff_molding_edit'),
  path('staff_molding_delete/<int:pk>/', StaffMoldingDeleteView.as_view(), name='staff_molding_delete'),

  path('staff_user_list/', StaffUserListView.as_view(), name='staff_user_list'),
  path('staff_user_detail/<int:pk>/', StaffUserDetailView.as_view(), name='staff_user_detail'),
  path('staff_user_delete/<int:pk>/', StaffUserDeleteView.as_view(), name='staff_user_delete'),

  path('staff_shipping_list/',StaffShippingListView.as_view(),name='staff_shipping_list'),
  path('staff_shipping_detail/<int:pk>/',StaffShippingDetailView.as_view(),name='staff_shipping_detail'),
  path('staff_shipping_delete/<int:pk>/',StaffShippingDeleteView.as_view(),name='staff_shipping_delete'),

]

production_control_project/urls.py
from django.contrib import admin
from django.urls import path, include
from django.views.generic import RedirectView

from django.conf import settings
from django.conf.urls.static import static


urlpatterns = [
    path('', RedirectView.as_view(url='/accounts/home/', permanent=True)),
    path('admin/', admin.site.urls),
    path('accounts/', include('accounts.urls')),
    path('daily_report/', include('daily_report.urls')),
    path('product_management/',include('product_management.urls'))
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

daily_report/models.py
from django.db import models

# Create your models here.
from django.db import models
from accounts.models import Users, Departments


#製品情報
class Products(models.Model):
    name = models.CharField(max_length=255,verbose_name="製品名")
    code = models.CharField(max_length=50,verbose_name="製品コード")
    quantity = models.IntegerField(verbose_name="製品取り数")
    memo = models.CharField(max_length=255,blank=True, null=True,verbose_name="製品メモ")
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)

    class Meta:
        verbose_name = '製品情報'
        db_table = 'products'

    def __str__(self):
        return self.name + ':' + self.code 


#業務内容
class Business(models.Model):
    department = models.ForeignKey(
        Departments, on_delete=models.CASCADE, verbose_name='部署情報'
    )
    name = models.CharField(max_length=50,verbose_name="業務名")
    business_content = models.CharField(max_length=255,verbose_name="業務内容")

    class Meta:
        verbose_name = '業務内容'
        db_table = 'business'

    def __str__(self):
        return self.department.name + ':' + self.name



#日報テーブル
class Report(models.Model):
    user = models.ForeignKey(
        Users, on_delete=models.CASCADE,verbose_name="ユーザー"
    )
    #製品情報紐付け
    product = models.ForeignKey(
        Products, on_delete=models.CASCADE,verbose_name="製品情報"
    )
    #業務内容紐付け
    business = models.ForeignKey(
        Business, on_delete=models.CASCADE,verbose_name="業務内容"
    )
    #ユーザー情報紐付け
    memo = models.CharField(max_length=255,blank=True, null=True,verbose_name="引き継ぎ",)
    lot_number = models.CharField(max_length=10, verbose_name='ロッド番号',default='')
    good_product= models.IntegerField(null=True,blank=True,verbose_name="優良数")
    bad_product= models.IntegerField(null=True,blank=True,verbose_name="不良数")
    status = models.CharField(max_length=10, null=True, blank=True, verbose_name="作業状況",)
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)

    class Meta:
        verbose_name = '日報'
        db_table = "report"


    def __str__(self):
        return self.created_at.strftime('%Y-%m-%d') + ':' + self.user.username + ':' + self.product.name + ':' + self.lot_number + ':' + self.business.name

    

templates/staff/staff_business_delete.html
{% extends 'base_staff.html' %}

{% block content %}
<h2>- 業務内容削除- </h2>
<p><strong>業務内容を削除してもよろしいですか？</strong></p>
<form method="POST">
    {% csrf_token %}
    <h3>- 業務名: {{ business.name }} -</h3>
    <p>部署:{{ business.department.name }}</p>
    <p>業務内容: {{ business.business_content }}</p>
    <input type="submit" value="削除">
</form>
<a href="{% url 'product_management:staff_business_list' %}">リストに戻る</a>
{% endblock %}

templates/staff/staff_business_list.html
{% extends 'base_staff.html' %}

{% block content %}
<h2>- 業務内容リスト -</h2>
<button><a href="{% url 'product_management:staff_business_create' %}">業務を作成する</a></button>
{% for department in department_data %}
    <h3>部署名: {{ department.name }}</h2>
    <table>
        <thead>
            <tr>
                <th>業務名</th>
                <th></th>
                <th>業務内容</th>
            </tr>
        </thead>
        <tbody>
            {% for business in business_data %}
                {% if business.department == department %}
                <tr>
                    <td>{{ business.name }} -</td>
                    <td></td>
                    <td>{{ business.business_content }}</td>

                    <td><button><a href="{% url 'product_management:staff_business_delete' business.id %}">削除</a></button></td>
          
                </tr>
                {% endif %}
            {% empty %}
                <tr>
                    <td colspan="3">該当する業務がありません.</td>
                </tr>
            {% endfor %}
        </tbody>
    </table>
{% endfor %}
{% endblock %}

templates/staff/staff_home.html
{% extends 'base_staff.html' %}

{% block content %}
<h2>- 出勤状況 -</h2>

<h3>製造部</h3>
<ul>
    {% for user in department_users %}
        {% if user.department.name == '製造部' %}
            <li>{{ user.username }}</li>
        {% endif %}
    {% endfor %}
</ul>

<h3>検査部</h3>
<ul>
    {% for user in department_users %}
        {% if user.department.name == '検査部' %}
            <li>{{ user.username }}</li>
        {% endif %}
    {% endfor %}
</ul>

<h3>出荷部</h3>
<ul>
    {% for user in department_users %}
        {% if user.department.name == '出荷部' %}
            <li>{{ user.username }}</li>
        {% endif %}
    {% endfor %}
</ul>
{% endblock %}

templates/staff/staff_molding_list.html
{% extends 'base_staff.html' %}

{% block content %}
<h2>- 成形品一覧 -</h2>
<!-- 成形品一覧 -->
{% if grouped_molding %}
<ul>
    {% for grouped_molding_item in grouped_molding %}
    <h2>{{ grouped_molding_item.product__name }}</h2> <!-- Display the product name as a header -->

    <table>
        <thead>
            <tr>
                <td>製品名</td>
                <td>ロッド番号</td>
                <td>優良成形数</td>
                <td>不良成形数</td>
                <td>成形担当者</td>
                <td>引き継ぎメモ</td>
            </tr>
        </thead>
        <tbody>
            {% for molding in staffmolding %}
              {% if molding.product.name == grouped_molding_item.product__name %}
              <tr>
                <td>{{ molding.product.name }}</td>
                <td>{{ molding.lot_number }}</td>
                <td>{{ molding.good_molding }}</td>
                <td>{{ molding.bad_molding }}</td>
                <td>{{ molding.user.username }}</td>
                <td>{{ molding.memo }}</td>

                <td><td><button><a href="{% url 'product_management:staff_molding_edit' molding.id %}">編集</a></button></td></td>
                <td><td><button><a href="{% url 'product_management:staff_molding_delete' molding.id %}">削除</a></button></td></td>
              </tr>
              {% endif %}
            {% empty %}
            <tr>
                <td colspan="6">{{ grouped_molding_item.product__name }}.</td>
            </tr>
            {% endfor %}
        </tbody>
    </table>
    <p>{{ grouped_molding_item.product__name }}合計優良成形数: {{ grouped_molding_item.total_good_molding }}</p>
    {% endfor %}
</ul>
{% endif %}

<a href="{% url 'product_management:staff_home' %}">ホーム画面(staff)</a>

{% endblock %}

templates/staff/staff_product_delete.html
{% extends "base_staff.html" %}

{% block content %}
<h2>- 製品情報削除 -</h2>
<p><strong>在庫を削除してもよろしいですか？</strong></p>
<form method="POST">
    {% csrf_token %}
    <p>製品名:{{ products.name }}</p>
    <p>製品コード:{{ products.code }}</p>
    <p>製品取り数:{{ products.quantity }}</p>
    <p>引き継ぎ:{{ products.memo }}</p>
   
    
    
    <input type="submit" value="削除">
</form>

<a href="{% url 'product_management:staff_product_list' %}">製品情報一覧に戻る</a>


{% endblock %}

templates/staff/staff_product_list.html
{% extends 'base_staff.html' %}

{% block content %}

<!--ユーザー一覧-->
<h2>- 製品情報 -</h2>

<button><a href="{% url 'product_management:staff_product_create' %}">製品情報を入力する</a></button>
{% if products %}
<ul>
        <table>
            <thead>
                <tr>
                    <th>製品名</th>
                    <th>製品コード</th>
                    <th>製品取り数</th>
                    <th>引き継ぎ</th>
                </tr>
            </thead>
            <tbody>
                {% for product in products %}
                <tr>
                    <td>{{ product.name }}</td>
                    <td>{{ product.code }}</td>
                    <td>{{ product.quantity }}</td>
                    <td>{{ product.memo }}</td>
                    <td><button><a href="{% url 'product_management:staff_product_edit' product.id %}">編集</a></button></td>
                    <td><button><a href="{% url 'product_management:staff_product_delete' product.id %}">削除</a></button></td>

                </tr>
                {% endfor %}
            </tbody>
        </table>
</ul>
{% endif %}

<a href="{% url 'product_management:staff_home' %}">ホーム画面</a>
{% endblock %}

templates/staff/staff_report_edit.html
{% extends 'base_staff.html' %}

{% block content %}
<h2>- 日報編集 -</h2>
<form method="POST" >
    {% csrf_token %}
    {{ form.as_p }}
    <input type="submit" value="編集する">
</form>

<button><a href="{% url 'product_management:staff_report_list' %}">日報一覧に戻る</a></button>
{% endblock %}

templates/staff/staff_report_list.html
{% extends 'base_staff.html' %}

{% block content %}
<h2>- 日報確認 -</h2>


<form method="GET">
    {{ form.as_p }}
    <button type="submit">表示</button>
</form>

{% regroup report_list by business.name as business_reports %}
{% if report_list %}
<table>
    <thead>
        <tr>
            <th>作業日</th>
            <th>作業者</th>
            <th>製品名</th>
            <th>ロッドナンバー</th>
            <th>優良数</th>
            <th>不良数</th>
            <th>作業状況</th>
            <th>引き継ぎ</th>
        </tr>
    </thead>
    <tbody>
        {% for business_report in business_reports %}
        <tr>
            <td>業務内容:{{ business_report.grouper }}</td> <!-- Display the business name as a header -->
        </tr>
        <td></td>

        {% for report in business_report.list %}
            <tr>
                <td><strong>{{ report.created_at }} ,</strong></td>
                <td>{{ report.user.username }} ,</td>
                <td>{{ report.product.name }} ,</td>
                <td>{{ report.lot_number }} ,</td>
                <td>{{ report.good_product }} ,</td>
                <td>{{ report.bad_product }} ,</td>
                <td>{{ report.status }} ,</td>
                <td>{{ report.memo }}</td>

                <td><button><a href="{% url 'product_management:staff_report_edit' report.id %}">編集する</a></button></td>
                <td><button><a href="{% url 'product_management:staff_report_delete' report.id %}">削除する</a></button></td>
            </tr>
            {% empty %}
            <tr>
                <td colspan="3">日報がありません.</td>
            </tr>
        {% endfor %}
        {% endfor %}
    </tbody>
</table>
{% endif %}





{% endblock %}

templates/staff/staff_reportproductgraph.html
{% extends 'base_staff.html' %}

{% block content %}
<h2>- 製品別の生産数 -</h2>


<form method="GET">
    {{ form.as_p }}
    <button type="submit">表示</button>
</form>

{% if chart_image %}
<img src="data:image/png;base64, {{ chart_image }}" alt="生産グラフ">
{% endif %}

{% for name, product_info in products_data.items %}
    <p>製品名: {{ name }}</p>
    <ul>
        {% for product_name, product_data in product_info.products.items %}
        <p>製品名: {{ product_name }} - 優良数: {{ product_data.good_product }} - 不良数: {{ product_data.bad_product }}</p>
        {% endfor %}
        <p>総優良数: {{ product_info.total_good_product }}</p>
        <p>総不良数: {{ product_info.total_bad_product }}</p>
    </ul>
{% endfor %}



{% endblock %}

templates/staff/staff_shipping_detail.html
{% extends 'base.html' %}

{% block content %}
<h2>- 作業詳細 -</h2>
<p>出荷日:{{ shippings.shipping_day }}<p>
    <p>製品名:{{ shippings.product }}</p>
    <p>納品先:{{ shippings.delivery }}</p>
    <p>出荷担当者:{{ shippings.user }}</p>
    <p>出荷必要数:{{ shippings.shipments_required }}</p>
    <p>使用在庫1:{{ shippings.stock1 }}</p>
    <p>使用在庫2:{{ shippings.stock2 }}</p>
    <p>使用在庫3:{{ shippings.stock3 }}</p>
    <p>引き継ぎ:{{ shippings.memo }}</p>
    
    <p><strong>※削除するときは、在庫の編集から在庫数を必ず戻してください</strong></p>
    <p><button><a href="{% url 'product_management:staff_shipping_delete' shippings.id %}">削除</a></button></p>
    <button><a href="{% url 'product_management:staff_stock_list' %}">在庫を編集</a></button>
    

    <p><a href="{% url 'product_management:staff_shipping_list' %}">出荷リストに戻る</a></p>

{% endblock %}

templates/staff/staff_stock_delete.html
{% extends "base_staff.html" %}

{% block content %}
<h2>- 在庫削除 -</h2>
<p><strong>在庫を削除してもよろしいですか？</strong></p>

<form method="POST">
    {% csrf_token %}
    <p>製品名:{{ stock.product.name }}</p>
    <p>ロッドナンバー:{{ stock.lot_number }}</p>
    <p>成形担当者:{{ stock.molding_user }}</p>
    <p>成形日時:{{ stock.molding_time }}</p>
    <p>検査担当者:{{ stock.inspection_user }}</p>
    <p>検査日時:{{ stock.created_at }}</p>
    <p>在庫数:{{ stock.stocks }}</p>
    <p>引き継ぎ:{{ stock.memo }}</p>
    
    
    <input type="submit" value="削除">
</form>

<a href="{% url 'product_management:staff_stock_list' %}">在庫一覧に戻る</a>


{% endblock %}

templates/staff/staff_stock_list.html
{% extends 'base_staff.html' %}

{% block content %}

<!--作業一覧-->
<h2>- 在庫リスト -</h2>
{% if grouped_stocks %}
<ul>
    {% for grouped_stock in grouped_stocks %}
    <h2>{{ grouped_stock.product__name }}</h2> <!-- Display the product name as a header -->

    <table>
        <thead>
            <tr>
                <td>製品名</td>
                <td>ロッドナンバー</td>
                <td>成形担当者</td>
                <td>成形日時</td>
                <td>検査担当者</td>
                <td>検査日時</td>
                <td>在庫数</td>
                <td>引き継ぎ</td>
            </tr>
        </thead>
        <tbody>
            {% for stock in staffstocks %}
              {% if stock.product.name == grouped_stock.product__name %}
              <tr>
                <td>{{ stock.product.name }}</td>
                <td>{{ stock.lot_number }}</td>
                <td>{{ stock.molding_user }}</td>
                <td>{{ stock.molding_time }}</td>
                <td>{{ stock.inspection_user }}</td>
                <td>{{ stock.created_at }}</td>
                <td>{{ stock.stocks }}</td>
                <td>{{ stock.memo }}</td>

                {% if report.good_product is not None %}
                <td>{{ report.good_product }}</td>
                <td>{{ report.bad_product }}</td>
                {% endif %}

                <td><button><a href="{% url 'product_management:staff_stock_edit' stock.id %}">編集</a></button></td>
                <td><button><a href="{% url 'product_management:staff_stock_delete' stock.id %}">削除</a></button></td>
                
              </tr>
              {% endif %}
            {% endfor %}
        </tbody>
    </table>
    <p>{{ grouped_stock.product__name }}合計在庫数: {{ grouped_stock.total_stocks }}</p>
    {% endfor %}
</ul>
{% endif %}
<a href="{% url 'product_management:staff_home' %}">ホーム画面</a>


{% endblock %}

templates/staff/staff_user_detail.html
{% extends 'base_staff.html' %}

{% block content %}
{% if user %}
<h2>- 作業詳細 -</h2>
  
                <h3>{{ user.username }}</h3>
                <p>生年月日:{{ user.birthday }}</p>
                <p>緊急連絡先:{{ user.phone }}</p>
                <p>連絡先メールアドレス:{{ user.email }}</p>
                <p>所属部署:{{ user.department }}</p>

               
                <p><button><a href="{% url 'product_management:staff_user_delete' user.id %}">削除</a></button></p>
                
            </tr>
        </tbody>
    </table>
{% endif %}
    <button><a href="{% url 'product_management:staff_user_list' %}">リストに戻る</a></button>     

{% endblock %}

templates/staff/staff_user_list.html
{% extends 'base_staff.html' %}

{% block content %}

<!--ユーザー一覧-->
<h2>- 社員リスト -</h2>
{% if users %}
<ul>
        <table>
            <thead>
                <tr>
                    <th>ユーザー名</th>
                </tr>
            </thead>
            <tbody>
                {% for user in users %}
                <tr>
                    <td>{{ user.username }}</td>
                    <td><button><a href="{% url 'product_management:staff_user_detail' user.id %}">詳細画面</a></button></td>
                    <td><button><a href="{% url 'product_management:staff_user_delete' user.id %}">削除</a></button></td>
                    
                </tr>
                {% endfor %}
            </tbody>
        </table>
</ul>
{% endif %}

<a href="{% url 'product_management:staff_home' %}">ホーム画面</a>
{% endblock %}