accounts/urls.py
from django.urls import path
from .views import (
     HomeView, LoginUserView, RegistUserView, LogoutUserView,StaffUserView,
     ProfileView, ProfileEditView,PasswordChangeView,
     PasswordResetView,PasswordResetConfirmView
)

app_name = 'accounts'

urlpatterns = [
    path('home/', HomeView.as_view(), name='home'),
    path('login_user/', LoginUserView.as_view(), name='login_user'),
    path('regist_user/', RegistUserView.as_view(), name='regist_user'),
    path('staff_user/', StaffUserView.as_view(), name='staff_user'),
    path('profile/', ProfileView.as_view(), name='profile'),
    path('profile/<int:pk>/edit/', ProfileEditView.as_view(),name='profile_edit'),
    path('password_change/',PasswordChangeView.as_view(),name = 'password_change'),
    path('password_reset/', PasswordResetView.as_view(), name='password_reset'),
    path('password_reset/confirm/<uidb64>/<token>/', PasswordResetConfirmView.as_view(), name='password_reset_confirm'),
    path('logout_user/', LogoutUserView.as_view(), name='logout_user'),

]

daily_report/urls.py
from django.urls import path
from .views import (
    ReportListView ,ReportStartView ,ReportEndView,ReportDetailView,ReportDeleteView,
    RepoetStartInspectionView,ReportEndEditView,ReportLogoutConfirm,
    StockEditView,StockListView,StockDeleteView,
    ShippingStartView,ShippingDetailView,ShippingListView,ShippingDeleteView
)
app_name =  'daily_report'

urlpatterns = [
    path('report_list/', ReportListView.as_view(), name='report_list'),
    path('report_start/',ReportStartView.as_view(), name='report_start'),
    path('report_detail/<int:pk>/',ReportDetailView.as_view(),name='report_detail'),
    path('report_detail/<int:pk>/end/', ReportEndView.as_view(), name='report_end'),
    path('report_detail/<int:pk>/endedit/', ReportEndEditView.as_view(), name='report_endedit'),
    path('report_delete/<int:pk>/',ReportDeleteView.as_view(), name='report_delete'),
    path('report_start_inspection/',RepoetStartInspectionView.as_view(),name='report_start_inspection'),

    path('shipping_list/', ShippingListView.as_view(), name='shipping_list'),
    path('shipping_start/', ShippingStartView.as_view(), name='shipping_start'),
    path('shipping_detail/<int:pk>/',ShippingDetailView.as_view(),name='shipping_detail'),
    path('shipping_delete/<int:pk>/',ShippingDeleteView.as_view(),name='shipping_delate'),

    path('stocks_list/', StockListView.as_view(), name='stock_list'),
    path('stocks/<int:pk>/edit/', StockEditView.as_view(), name='stock_edit'),
    path('stocks_delete/<int:pk>/', StockDeleteView.as_view(), name='stock_delete'),

    path('logout/',ReportLogoutConfirm.as_view(),name='logout'),
]

product_management/urls.py
from django.urls import path
from .views import (
    StaffHomeView,StaffReportUserGraphView,StaffReportProductGraphView,
    StaffBusinessListView,StaffBusinessCreateView,StaffBusinessDeleteView,
    StaffProductCreateView,StaffProductListView,StaffProductEditView,StaffProductDeleteView,
    StaffStockListView,StaffStockEditView,StaffStockDeleteView,
    StaffReportListView, StaffReportEditView, StaffReportDeleteView,
    StaffMoldingListView, StaffMoldingEditView, StaffMoldingDeleteView,
    StaffUserListView,StaffUserDetailView,StaffUserDeleteView,
    StaffShippingListView,StaffShippingDetailView,StaffShippingDeleteView
)
app_name =  'product_management'

urlpatterns = [
  path('staff_home/',StaffHomeView.as_view(), name='staff_home'),
  path('staff_reportusergraph/',StaffReportUserGraphView.as_view(), name='staff_reportusergraph'),
  path('staff_reportproductgraph/',StaffReportProductGraphView.as_view(), name='staff_reportproductgraph'),

  path('staff_business_list/',StaffBusinessListView.as_view(), name='staff_business_list'),
  path('staff_business_create/',StaffBusinessCreateView.as_view(), name='staff_business_create'),
  path('staff_business_delete/<int:pk>/',StaffBusinessDeleteView.as_view(), name='staff_business_delete'),

  path('staff_stock_list/', StaffStockListView.as_view(), name='staff_stock_list'),
  path('staff_stock/<int:pk>/edit/', StaffStockEditView.as_view(), name='staff_stock_edit'),
  path('staff_stock_delete/<int:pk>/', StaffStockDeleteView.as_view(), name='staff_stock_delete'),

  path('staff_product_list/',StaffProductListView.as_view(), name='staff_product_list'),
  path('staff_product_create/', StaffProductCreateView.as_view(), name='staff_product_create'),
  path('staff_product/<int:pk>/edit/', StaffProductEditView.as_view(), name='staff_product_edit'),
  path('staff_product_delete/<int:pk>/', StaffProductDeleteView.as_view(), name='staff_product_delete'),

  path('staff_report_list/', StaffReportListView.as_view(), name='staff_report_list'),
  path('staff_report/<int:pk>/edit/', StaffReportEditView.as_view(), name='staff_report_edit'),
  path('staff_report_delete/<int:pk>/', StaffReportDeleteView.as_view(), name='staff_report_delete'),

  path('staff_molding_list/', StaffMoldingListView.as_view(), name='staff_molding_list'),
  path('staff_molding/<int:pk>/edit/', StaffMoldingEditView.as_view(), name='staff_molding_edit'),
  path('staff_molding_delete/<int:pk>/', StaffMoldingDeleteView.as_view(), name='staff_molding_delete'),

  path('staff_user_list/', StaffUserListView.as_view(), name='staff_user_list'),
  path('staff_user_detail/<int:pk>/', StaffUserDetailView.as_view(), name='staff_user_detail'),
  path('staff_user_delete/<int:pk>/', StaffUserDeleteView.as_view(), name='staff_user_delete'),

  path('staff_shipping_list/',StaffShippingListView.as_view(),name='staff_shipping_list'),
  path('staff_shipping_detail/<int:pk>/',StaffShippingDetailView.as_view(),name='staff_shipping_detail'),
  path('staff_shipping_delete/<int:pk>/',StaffShippingDeleteView.as_view(),name='staff_shipping_delete'),

]

production_control_project/urls.py
from django.contrib import admin
from django.urls import path, include
from django.views.generic import RedirectView

from django.conf import settings
from django.conf.urls.static import static


urlpatterns = [
    path('', RedirectView.as_view(url='/accounts/home/', permanent=True)),
    path('admin/', admin.site.urls),
    path('accounts/', include('accounts.urls')),
    path('daily_report/', include('daily_report.urls')),
    path('product_management/',include('product_management.urls'))
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

templates/base.html
<!DOCTYPE html>
<html lang="ja">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta name="format-detection" content="telephone=no" />
    <script src="https://code.jquery.com/jquery-3.6.0.min.js"></script>
    <title>{% block title %} 生産管理アプリ {% endblock title %}</title>
</head>
<body>
        <table>
            <tr>
                <td><h2>「作業日報&生産管理」</h2></td>
                {% if request.user.is_staff %}
                <td><button><a href="{% url 'product_management:staff_home' %}">ホーム画面</a></button></td>
                {% else %}
                <td><button><a href="{% url 'daily_report:report_list' %}">ホーム画面</a></button></td>
                {% endif %}
                <td><button onclick="confirmLogout()"><a href="#">ログアウトします</a></button></td>
                <td></td>
                <td><h3>{{ request.user.username }}さん</h3></td>
                <td><p><a href="{% url 'accounts:profile' %}">アカウント詳細</a></p></td>
            </tr>
        </table>
        <hr>
        {% block content %}
        {% endblock %}

    <script>
        function confirmLogout() {
            if (confirm("実行中の作業を終了してからログアウトすることをお勧めします。一日経つとデータを編集できなくなります。")) {
                window.location.href = "{% url 'accounts:logout_user' %}";
            }
        }
    </script>
</body>
</html>

templates/base_staff.html
<!DOCTYPE html>
<html lang="ja">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta name="format-detection" content="telephone=no" />
    <script src="https://code.jquery.com/jquery-3.6.0.min.js"></script>
    <title>{% block title %} 生産管理アプリ {% endblock title %}</title>
</head>
<body>
    <table>
        <tr>
            <td><h2>「作業日報&生産管理」</h2></td>
            <td><p>{{ request.user.username }}さん</p></td>
            <td><button><a href="{% url 'product_management:staff_home' %}">ホーム画面</a></button></td>
            <td><button><a href="{% url 'accounts:logout_user' %}">ログアウト</a></button></td>
            <td><p><a href="{% url 'accounts:profile' %}">アカウント詳細</a></p></td>
        </tr>
    </table>
    <hr>
    <p><a href="{% url 'product_management:staff_user_list' %}">社員一覧</a></p>
    <p><a href="{% url 'product_management:staff_report_list' %}">日報一覧</a></p>
    <p><a href="{% url 'product_management:staff_molding_list' %}">成形品一覧</a></p>
    <p><a href="{% url 'product_management:staff_stock_list' %}">在庫一覧</a></p> 
    <p><a href="{% url 'product_management:staff_shipping_list' %}">出荷一覧</a></p> 
    <p><a href="{% url 'product_management:staff_business_list' %}">業務内容作成</a></p>
    <p><a href="{% url 'product_management:staff_product_list' %}">製造情報作成</a></p>    
    <p><a href="{% url 'product_management:staff_reportusergraph' %}">成形者ごとの１ヶ月ごとの生産数(日報から)</a></p> 
    <p><a href="{% url 'product_management:staff_reportproductgraph' %}">製品ごとのの１ヶ月の生産数(日報から)</a></p>         
    <hr>  
    {% block content %}
    {% endblock %}
</body>
</html>

templates/home.html
<!DOCTYPE html>
<html lang="ja">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta name="format-detection" content="telephone=no" />
    <script src="https://code.jquery.com/jquery-3.6.0.min.js"></script>
    <title>{% block title %} 生産管理アプリ {% endblock title %}</title>
</head>
<body>

    <h1>株式会社</h1>
    <h2>- 生産管理アプリ -</h2>

    <nav>
        <p><button><a href="{% url 'accounts:login_user' %}">ログイン</a></button></p>
        <button><a href="{% url 'accounts:regist_user' %}">入社登録</a></button>
        <button><a href="{% url 'accounts:staff_user' %}">管理アカウント登録</a></button>
    </nav>

</body>
</html>

templates/login_user.html
<!DOCTYPE html>
<html lang="ja">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta name="format-detection" content="telephone=no" />
    <script src="https://code.jquery.com/jquery-3.6.0.min.js"></script>
    <title>{% block title %} 生産管理アプリ {% endblock title %}</title>
</head>
<body>

    <h1>株式会社</h1>
    <h2>- 生産管理アプリ -</h2>
    <hr>

    <h2>ログイン画面</h2>

    <!--パスワード変更されたらメッセージを表示する-->
    {% if messages %}
    <ul class="messages">
        {% for message in messages %}
        <li{% if message.tags %} class="{{ message.tags }}"{% endif %}>{{ message }}</li>
        {% endfor %}
    </ul>
    {% endif %}
    
    <form method="POST">
        {% csrf_token %}
        {{ form.as_p }}
        <input  type="submit" value="ログイン">
    </form>
    <p><button><a href="{% url 'accounts:password_reset' %}">パスワードを忘れた方</a></button></p>

    <a href="{% url 'accounts:home' %}">メインページに戻る</a>

</body>
</html>

templates/logout.html
{% extends 'base.html' %}

{% block content %}
<h1>所属部署:{{ user.department.name }}</h1>
<h2>本日の作業</h2>
<!--作業一覧-->

{% if lastreports %}
    <ul>
        <table >
            <thead>
                <tr>
                    <td>製品名</td>
                    <td>製品コード</td>
                    <td>業務内容</td>
                    <td>作業者</td>
                    <td>ロッド番号</td>
                    <td>作業状況</td>
                    <td>優良成形数</td>
                    <td>不良成形数</td>
                    <td>引き継ぎ</td>
                </tr>
            </thead>
            <tbody>
                {% for report in lastreports %}
                <tr>
                    <td>{{ report.product.name }}</td>
                    <td>{{ report.product.code }}</td>
                    <td>{{ report.business.name }}</td>
                    <td>{{ report.user.username }}</td>
                    <td>{{ report.lot_number }}</td>
                    <td><strong>{{ report.status }}</strong></td>
                    <td>{{ report.good_product }}</td>
                    <td>{{ report.bad_product }}</td>
                    <td>{{ report.memo }}</td>
                </tr>
                {% endfor %}
            </tbody>
        </table>
    </ul>
    {% endif %}

<p>本日の作業を終了しますか？</p>

{% if request.user.department.name == '出荷部' %}
<p><strong>※作業を確認してからログアウトすることをお勧めします。一日経つとデータを編集できなくなります。※</strong></p>
{% else %}
<p><strong>※実行中の作業を終了してからログアウトすることをお勧めします。一日経つとデータを編集できなくなります。※</strong></p>
{% endif %}

<button><a href="{% url 'accounts:logout_user' %}">ログアウトします</a></button>
<button><a href="{% url 'daily_report:report_list' %}">ログアウトしません(ホームに戻る)</a></button>

{% endblock %}

templates/regist_user.html
<!DOCTYPE html>
<html lang="ja">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta name="format-detection" content="telephone=no" />
    <script src="https://code.jquery.com/jquery-3.6.0.min.js"></script>
    <title>{% block title %} 生産管理アプリ {% endblock title %}</title>
</head>
<body>

    <h1>株式会社</h1>
    <h2>- 生産管理アプリ -</h2>
    <hr>

    <h2>入社登録画面</h2>
    <form method="POST">
    {% csrf_token %}
    {{ form.as_p }}
    <input  type="submit" value="社員登録">
    </form>

    
    <a href="{% url 'accounts:home' %}">メインページに戻る</a>

</body>
</html>

templates/staff_user.html
<!DOCTYPE html>
<html lang="ja">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta name="format-detection" content="telephone=no" />
    <script src="https://code.jquery.com/jquery-3.6.0.min.js"></script>
    <title>{% block title %} 生産管理アプリ {% endblock title %}</title>
</head>
<body>

    <h1>株式会社</h1>
    <h2>- 生産管理アプリ -</h2>
    <hr>

    <h2>管理者登録画面</h2>
    <form method="POST">
        {% csrf_token %}
        {{ form.as_p }}
        <input  type="submit" value="管理アカウント作成">
    </form>

    <a href="{% url 'accounts:home' %}">メインページに戻る</a>

</body>
</html>