accounts/urls.py
from django.urls import path
from .views import (
     HomeView, LoginUserView, RegistUserView, LogoutUserView,StaffUserView,
     ProfileView, ProfileEditView,PasswordChangeView,
     PasswordResetView,PasswordResetConfirmView
)

app_name = 'accounts'

urlpatterns = [
    path('home/', HomeView.as_view(), name='home'),
    path('login_user/', LoginUserView.as_view(), name='login_user'),
    path('regist_user/', RegistUserView.as_view(), name='regist_user'),
    path('staff_user/', StaffUserView.as_view(), name='staff_user'),
    path('profile/', ProfileView.as_view(), name='profile'),
    path('profile/<int:pk>/edit/', ProfileEditView.as_view(),name='profile_edit'),
    path('password_change/',PasswordChangeView.as_view(),name = 'password_change'),
    path('password_reset/', PasswordResetView.as_view(), name='password_reset'),
    path('password_reset/confirm/<uidb64>/<token>/', PasswordResetConfirmView.as_view(), name='password_reset_confirm'),
    path('logout_user/', LogoutUserView.as_view(), name='logout_user'),

]

daily_report/urls.py
from django.urls import path
from .views import (
    ReportListView ,ReportStartView ,ReportEndView,ReportDetailView,ReportDeleteView,
    RepoetStartInspectionView,ReportEndEditView,ReportLogoutConfirm,
    StockEditView,StockListView,StockDeleteView,
    ShippingStartView,ShippingDetailView,ShippingListView,ShippingDeleteView
)
app_name =  'daily_report'

urlpatterns = [
    path('report_list/', ReportListView.as_view(), name='report_list'),
    path('report_start/',ReportStartView.as_view(), name='report_start'),
    path('report_detail/<int:pk>/',ReportDetailView.as_view(),name='report_detail'),
    path('report_detail/<int:pk>/end/', ReportEndView.as_view(), name='report_end'),
    path('report_detail/<int:pk>/endedit/', ReportEndEditView.as_view(), name='report_endedit'),
    path('report_delete/<int:pk>/',ReportDeleteView.as_view(), name='report_delete'),
    path('report_start_inspection/',RepoetStartInspectionView.as_view(),name='report_start_inspection'),

    path('shipping_list/', ShippingListView.as_view(), name='shipping_list'),
    path('shipping_start/', ShippingStartView.as_view(), name='shipping_start'),
    path('shipping_detail/<int:pk>/',ShippingDetailView.as_view(),name='shipping_detail'),
    path('shipping_delete/<int:pk>/',ShippingDeleteView.as_view(),name='shipping_delate'),

    path('stocks_list/', StockListView.as_view(), name='stock_list'),
    path('stocks/<int:pk>/edit/', StockEditView.as_view(), name='stock_edit'),
    path('stocks_delete/<int:pk>/', StockDeleteView.as_view(), name='stock_delete'),

    path('logout/',ReportLogoutConfirm.as_view(),name='logout'),
]

production_control_project/urls.py
from django.contrib import admin
from django.urls import path, include
from django.views.generic import RedirectView

from django.conf import settings
from django.conf.urls.static import static


urlpatterns = [
    path('', RedirectView.as_view(url='/accounts/home/', permanent=True)),
    path('admin/', admin.site.urls),
    path('accounts/', include('accounts.urls')),
    path('daily_report/', include('daily_report.urls')),
    path('product_management/',include('product_management.urls'))
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

templates/report/report_delete.html
{% extends "base.html" %}

{% block content %}
<h2>- 作業削除 -</h2>
<p><strong>作業を削除してもよろしいですか？</strong></p>
<form method="POST">
    {% csrf_token %}
    <p>製品名:{{ report.product.name }}</p>
    <p>製品コード: {{ report.product.code }}</p>
    <p>ロッドナンバー: {{ report.lot_number }}</p>
    <p>作業日時: {{ report.created_at.year }}/{{ report.created_at.month }}/{{ report.created_at.day }}</p>
    <input type="submit" value="削除">
</form>
<p><a href="{% url 'daily_report:report_list' %}">ホーム画面に戻る</a></p>
{% endblock %}

templates/report/report_detail.html
{% extends 'base.html' %}

{% block content %}
<h2>- 作業詳細 -</h2>
    <p>業務内容:{{ reportdetail.business.name }}</p>
    <p>製品名: {{ reportdetail.product.name }}</p>
    <p>製品コード: {{ reportdetail.product.code }}</p>
    <p>製品取り数: {{ reportdetail.product.quantity }}</p>
    <p>ロッドナンバー: {{ reportdetail.lot_number }}</p>
    <p>成形時メモ: {{ reportdetail.product.memo }}</p>

    <!--request.userの部署名が検査部だったら表示-->
    {% if inspection_good_molding %}
    <p>成形品優良数: {{ inspection_good_molding }}</p>
    <p>成形品不良数: {{ inspection_bad_molding }}</p>
    <p>成形担当者: {{ inspection_molding_user }}</p>
    {% endif %}

    {% if request.user.department.name == '出荷部' %}
    <p>必要出荷数: {{ reportdetail.good_product }}</p>
    {% endif %}

    <p>作業者: {{ reportdetail.user.username }}</p>
    <p>作業日時: {{ reportdetail.created_at.year }}/{{ reportdetail.created_at.month }}/{{ reportdetail.created_at.day }}</p>
    <br>
    
    {% if reportdetail.good_product %}
    <p>{{ reportdetail.business.name }}優良数：{{ reportdetail.good_product }}</p>
    <p>{{ reportdetail.business.name }}不良数: {{ reportdetail.bad_product }}</p>
        {% if request.user.department.name != '出荷部' %}
        <p><button><a href="{% url 'daily_report:report_endedit' reportdetail.id %}">結果を編集する</a></button></p>
        {% endif %}
    {% else %}
        {% if request.user.department.name == '出荷部' %}
        <p><button><a href="{% url 'daily_report:report_shippingend' reportdetail.id %}">作業を終了する</a></button></p>
        {% else %}
        <p><button><a href="{% url 'daily_report:report_end' reportdetail.id %}">作業を終了する</a></button></p>
        {% endif %}
    {% endif %}

    <p><button><a href="{% url 'daily_report:report_delete' reportdetail.id %}">作業を削除する</a></button></p>

    <p><a href="{% url 'daily_report:report_list' %}">ホーム画面に戻る</a></p>

{% endblock %}

templates/report/report_end.html
{% extends "base.html" %}

{% block content %}
<h2>- 作業終了 -</h2>
<h3>終了後の結果を記入し、終了をしてください。</h3>
<form method="POST">
    {% csrf_token %}
    <div>
        {{ form.product.label_tag }}
        {{ form.product }}
    </div>
    <div>
        {{ form.business.label_tag }} 
        {{ form.business }}
    </div>
    <div>
        {{ form.lot_number.label_tag }} 
        {{ form.lot_number }}
    </div>
    <div>
        {{ form.user.label_tag }}
        {{ form.user }}
    </div>
    <div>
        {{ form.quantity.label_tag }}
        {{ form.quantity }}
    </div>
    <div>
        {{ form.sets.label_tag }}
        {{ form.sets }}
        {{ form.sets.errors }}
    </div>
    <div>
        {{ form.bad_product.label_tag }}
        {{ form.bad_product }}
        {{ form.bad_product.errors }}
    </div>
    <div>
        {{ form.memo.label_tag }}
        {{ form.memo }}
    </div>
    
    <input type="submit" value="終了する">
</form>
<p><a href="{% url 'daily_report:report_list' %}">ホーム画面に戻る</a></p>
{% endblock %}

templates/report/report_end_edit.html
{% extends "base.html" %}

{% block content %}
<h2>- 作業終了後編集ページ -</h2>
<form method="POST">
    {% csrf_token %}
    {% csrf_token %}
    <div>
        {{ form.product.label_tag }}
        {{ form.product }}
    </div>
    <div>
        {{ form.business.label_tag }}
        {{ form.business }}
    </div>
    <div>
        {{ form.lot_number.label_tag }}
        {{ form.lot_number }}
    </div>
    <div>
        {{ form.user.label_tag }}
        {{ form.user }}
    </div>
    <div>
        {{ form.good_product.label_tag }}
        {{ form.good_product }}
        {{ form.good_product.errors }}
    </div>
    <div>
        {{ form.bad_product.label_tag }}
        {{ form.bad_product }}
        {{ form.bad_product.errors }}
    </div>
    <div>
        {{ form.memo.label_tag }}
        {{ form.memo }}
    </div>
    <input type="submit" value="編集する">
</form>

<p><a href="{% url 'daily_report:report_list' %}">ホーム画面に戻る</a></p>
{% endblock %}

templates/report/report_list.html
{% extends 'base.html' %}

{% block content %}
<h2>- 所属部署:{{ user.department.name }} -</h2>

{% if request.user.department.name == '製造部' %}
    <button><a href="{% url 'daily_report:report_start' %}">作業をスタートする</a></button>
    {% elif request.user.department.name == '検査部' %}
    <button><a href="{% url 'daily_report:report_start_inspection' %}">作業をスタートする</a></button>
    {% elif request.user.department.name == '出荷部' %}
    <button><a href="{% url 'daily_report:shipping_start'%}">出荷記録を入力する</a></button>
    {% else %}
    <button><a href="{% url 'daily_report:report_start' %}">作業をスタートする</a></button>
{% endif %}

<!--作業一覧-->
{% if request.user.department.name == '出荷部' %}
    {% if shippings %}
        <h3>出荷業務</h3>
            <ul>
                <table>
                    <thead>
                        <tr>
                            <td>製品名</td>
                            <td>納品先</td>
                            <td>出荷日</td>
                            <td>出荷数</td>
                            <td>引き継ぎ</td>
                            <td>使用在庫1</td>
                            <td>使用在庫2</td>
                            <td>使用在庫3</td>
                            
                        </tr>
                    </thead>
                    <tbody>
                        {% for shipping in shippings %}
                            <tr>
                                <td>{{ shipping.product }}</td>
                                <td>{{ shipping.delivery }}</td>
                                <td>{{ shipping.shipping_day }}</td>
                                <td>{{ shipping.shipments_required }}</td>
                                <td>{{ shipping.memo }}</td>
                                <td>{{shipping.stock1.lot_number}}</td>
                                <td>{{shipping.stock2.lot_number}}</td>
                                <td>{{shipping.stock3.lot_number}}</td>
                                <td><button><a href="{% url 'daily_report:shipping_detail' pk=shipping.id %}">出荷の詳細を見る</a></button></td>
                            </tr>
                        {% endfor %}
                    </tbody>
                </table>
            </ul>
    {% endif %}
    <h4>※出荷業務の入力間違いがあれば、必ず在庫を修正してください。</h4>
    <p><button><a href="{% url 'daily_report:stock_list' %}">在庫を編集できます。</a></button></p>
{% else %}
    {% if reports %}
    <ul>
        <table >
            <thead>
                <tr>
                    <td>製品名</td>
                    <td>製品コード</td>
                    <td>業務内容</td>
                    <td>作業者</td>
                    <td>ロッド番号</td>
                    <td>作業状況</td>
                    <td>優良成形数</td>
                    <td>不良成形数</td>
                </tr>
            </thead>
            <tbody>
                {% for report in reports %}
                <tr>
                    <td>{{ report.product.name }}</td>
                    <td>{{ report.product.code }}</td>
                    <td>{{ report.business.name }}</td>
                    <td>{{ report.user.username }}</td>
                    <td>{{ report.lot_number }}</td>
                    <td><strong>{{ report.status }}</strong></td>

                    {% if report.good_product is not None %}
                    <td>{{ report.good_product }}</td>
                    <td>{{ report.bad_product }}</td>
                    {% endif %}

                    {% if report.status == '終了' %}
                    <td><button><a href="{% url 'daily_report:report_detail' pk=report.id %}">結果を編集する</a></button></td>
                    {% else %}
                    <td><button><a href="{% url 'daily_report:report_detail' pk=report.id %}">作業を終了する</a></button></td>
                    {% endif %}

                   
                </tr>
                {% endfor %}
            </tbody>
        </table>
    </ul>
    {% endif %}
{% endif %}



<p><button><a href="{% url 'daily_report:logout' %}">本日の作業を終了する</a></button></p>

{% endblock %}

templates/report/report_shipping_end.html
{% extends "base.html" %}

{% block content %}
<h1>作業終了</h1>
<form method="POST">
    {% csrf_token %}
    <div>
        {{ form.product.label_tag }}
        {{ form.product_name }}
    </div>
    <div>
        {{ form.delivery.label_tag }} 
        {{ form.delivery }}
    </div>
    <div>
        {{ form.user.label_tag }} 
        {{ form.user }}
    </div>
    <div>
        {{ form.shipments_required.label_tag }} 
        {{ form.shipments_required }}
    </div>
    <div>
        {{ form.shipping_day.label_tag }}
        {{ form.shipping_day }}
    </div>
    <div>
        {{ form.stock1.label_tag }}
        {{ form.stock1 }}
    </div>
    <div>
        {{ form.stock2.label_tag }}
        {{ form.stock2 }}
    </div>
    <div>
        {{ form.stock3.label_tag }}
        {{ form.stock3 }}
    </div>
    <div>
        {{ form.memo.label_tag }}
        {{ form.memo }}
    </div>
    
    <input type="submit" value="終了する">
</form>
<button><a href="{% url 'daily_report:report_list' %}">ホーム画面に戻る</a></button>
{% endblock %}

templates/report/report_start.html
{% extends "base.html" %}

{% block content %}
<h2>- 作業開始ページ -</h2>
<h3>製品を選んで、作業を開始してください</h3>
<form method="POST">
    {% csrf_token %}
    <div>
        {{ form.product.label_tag }}
        {{ form.product }}
    </div>
    <div>
        {{ form.business.label_tag }}
        {{ form.business }}
    </div>
    <input type="submit" value="スタートする">
</form>

<p><a href="{% url 'daily_report:report_list' %}">ホーム画面に戻る</a></p>
{% endblock %}

templates/report/report_start_inspection.html
{% extends "base.html" %}

{% block content %}
<h2>- 作業開始ページ -</h2>
<h3>検査するロッド番号を選択して開始してください</h3>
<form method="POST">
    {% csrf_token %}
    {{ form.as_p }}
    <input type="submit" value="スタートする">
</form>

<p><a href="{% url 'daily_report:report_list' %}">ホーム画面に戻る</a></p>
{% endblock %}